# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.17.2

# Mod Properties
modid = expandeddelight
mod_version = 0.4.0.0
maven_group = com.ianm1647
archives_base_name = expandeddelight

# Dependencies
fabric_version=0.116.5+1.21.1
delight_version=1.21.1-3.0.1+refabricated
rei_version=16.0.799
modmenu_version=11.0.2
omega_version=1.4.4-1.21

# Fabric API
